name: Build Libbox.xcframework

on:
  workflow_dispatch:

jobs:
  build-libbox:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Clone sing-box
        run: git clone --depth=1 https://github.com/SagerNet/sing-box.git

      - name: Run build script
        run: |
          bash build-libbox.sh

      - name: Zip artifact
        run: zip -r Libbox.xcframework.zip Libbox.xcframework

      - uses: actions/upload-artifact@v4
        with:
          name: Libbox.xcframework
          path: Libbox.xcframework.zip
