name: Build Libbox.xcframework

on:
  workflow_dispatch:

jobs:
  build-libbox:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH="$PATH:$(go env GOPATH)/bin"
          gomobile init

      - name: Clone sing-box
        run: |
          git clone --depth=1 https://github.com/SagerNet/sing-box.git

      - name: Build frameworks
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          cd sing-box/experimental/libbox
          go mod tidy

          gomobile bind -tags with_utls -target=ios/arm64 -o libbox_ios_arm64.framework .
          gomobile bind -tags with_utls -target=iossimulator/arm64 -o libbox_iossim_arm64.framework .
          gomobile bind -tags with_utls -target=macos/arm64 -o libbox_macos_arm64.framework .

          xcodebuild -create-xcframework \
            -framework libbox_ios_arm64.framework \
            -framework libbox_iossim_arm64.framework \
            -framework libbox_macos_arm64.framework \
            -output Libbox.xcframework

      - name: Zip artifact
        run: zip -r Libbox.xcframework.zip Libbox.xcframework

      - uses: actions/upload-artifact@v4
        with:
          name: Libbox.xcframework
          path: Libbox.xcframework.zip
