name: Build Libbox.xcframework

on:
  workflow_dispatch:

jobs:
  build-libbox:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH="$PATH:$(go env GOPATH)/bin"
          gomobile init

      - name: Clone sing-box source
        run: |
          git clone --depth=1 https://github.com/SagerNet/sing-box.git

      - name: Build Libbox with uTLS
        run: |
          cd sing-box/experimental/libbox
          go mod tidy
          export PATH="$PATH:$(go env GOPATH)/bin"
          gomobile bind -tags with_utls -target=ios,macos -o libbox.framework .

      - name: Create XCFramework
        run: |
          xcodebuild -create-xcframework -framework libbox.framework -output Libbox.xcframework

      - name: Zip artifact
        run: zip -r Libbox.xcframework.zip Libbox.xcframework

      - uses: actions/upload-artifact@v4
        with:
          name: Libbox.xcframework
          path: Libbox.xcframework.zip
